sudo: required
language: node_js
node_js:
  - '10'
env:
  global:
    secure: YmiTg1whqSBdsS5yfuUs8X+YXYjlQQHa8M6ZUXWqvZz0QG3Zn0xqQrXULPuj/Iu0tNkOl7K9hij7fIdeTjls9Ovzy2nImEzEosqHUr8Y4u5Ld39ckbLPJjxh34pPbq9WKhLIGJY6rC8U/mDS3Ptt8DQH6ceQemdWMyDTHRyGYnVzkVpxzRuy6Y+lr/TUJBu/qyx5ITQRQ+XCvx1Pc9z9fYiNtDY88GZ+mY3E5W6VeuzsTHxPrNHW4Y89tLv7pxLQqTk5xgWNA7DkloYzBpxFrkhescIkdyNCjntZfN0WuBNFFSWznxOo2YPDRiA99lE8lKn43/dTg0ubAnDFNlj+PcGHgcSrFPLi6G8Tzq4c9VbVT7ljXR7OTEr485zZkAIFOgFKHEjTHSpI2p+7lDVpmzZYjmKDrlBkoNc2fl12kRu3sISmguu4bphfhUka3qX9vyoczBdN5b2NRJaZXWX3+8UMjzz63XtfDpiF6VleA23fwKVmzckG13zQr6cqzqFs43XtOo/t4dbN214UoSOsoLfLhie798I39yfAcFL+AWyfA2SPKfzGagIkf/YFUnR5bYQNOxRa21cOV6dlPXeAGj7I3KzgkQGbpyHof3PeZcOaeFH/mTGKm8+5LizlKjE7B1G6j4fM9imRd4omej1laj0TsXugb7VnyvyAOOCOJaE=
before_install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  target-branch: main
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: coffeeeeffoc/blog.github.io
  github-token: $REPO_TOKEN
  keep-history: true
  on:
    branch: main
